---
format_version: '23'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

project_type: flutter

# Trigger налаштування
triggers:
  push:
    - branch: main
      workflow: android_firebase
  pull_request:
    - source_branch: "*"
      workflow: android_firebase

# Workflows
workflows:
  
  android_firebase:
    description: Build Android APK для Firebase App Distribution
    steps:
    
    # 1. Активувати SSH key для Git
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    
    # 2. Клонувати репозиторій
    - git-clone@8: {}
    
    # 3. Встановити Flutter
    - flutter-installer@0:
        inputs:
        - version: 3.24.0
        - is_update: 'false'
    
    # 4. Cache Dart packages
    - restore-dart-cache@2: {}
    
    # 5. Створити Firebase конфігураційні файли з секретів
    - script@1:
        title: Setup Firebase Config Files
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            cd voteeasy
            
            echo "?? Creating Firebase configuration files..."
            
            # Створюємо google-services.json з секрету
            if [ -n "$GOOGLE_SERVICES_JSON" ]; then
                echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
                echo "? google-services.json created"
            else
                echo "? GOOGLE_SERVICES_JSON secret is not set!"
                exit 1
            fi
            
            # Створюємо firebase_options.dart з секрету
            if [ -n "$FIREBASE_OPTIONS_DART" ]; then
                echo "$FIREBASE_OPTIONS_DART" > lib/firebase_options.dart
                echo "? firebase_options.dart created"
            else
                echo "? FIREBASE_OPTIONS_DART secret is not set!"
                exit 1
            fi
    
    # 6. Flutter pub get
    - script@1:
        title: Flutter packages get
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            cd voteeasy
            flutter pub get
    
    # 7. Flutter analyze (перевірка коду)
    - script@1:
        title: Flutter analyze
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            cd voteeasy
            flutter analyze || true
        is_always_run: false
    
    # 8. Save Dart cache
    - save-dart-cache@1: {}
    
    # 9. Build Android APK (release)
    - script@1:
        title: Build Android APK (Release)
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            echo "?? Building Flutter Android APK in RELEASE mode..."
            cd voteeasy
            flutter build apk --release
            
            APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
            
            if [ -f "$APK_PATH" ]; then
                echo "? APK built successfully: $APK_PATH"
                ls -lh "$APK_PATH"
                
                # Export для Firebase
                envman add --key ANDROID_APK_PATH --value "$BITRISE_SOURCE_DIR/voteeasy/$APK_PATH"
                
                # Copy to deploy dir
                cp "$APK_PATH" "$BITRISE_DEPLOY_DIR/VoteEasy.apk"
                echo "? APK copied to artifacts"
            else
                echo "? APK not found!"
                exit 1
            fi
    
    # 10. Verify Firebase configuration
    - script@1:
        title: Verify Firebase App ID
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            echo "?? Checking Firebase configuration..."
            echo "App ID: $FIREBASE_APP_ID_ANDROID"
            echo "APK Path: $ANDROID_APK_PATH"
            
            if [ -z "$FIREBASE_APP_ID_ANDROID" ]; then
                echo "? FIREBASE_APP_ID_ANDROID is not set!"
                echo "Please add it in Bitrise Secrets"
                exit 1
            fi
            
            if [ ! -f "$ANDROID_APK_PATH" ]; then
                echo "? APK file not found at $ANDROID_APK_PATH"
                exit 1
            fi
            
            echo "? Firebase config looks good"
    
    # 11. Firebase App Distribution (Android)
    - script@1:
        title: Firebase App Distribution
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -ex
            
            echo "?? Uploading to Firebase App Distribution..."
            echo "APK: $ANDROID_APK_PATH"
            echo "App ID: $FIREBASE_APP_ID_ANDROID"
            echo "Branch: $BITRISE_GIT_BRANCH"
            echo "Build: #$BITRISE_BUILD_NUMBER"
            
            # Verify APK exists
            if [ ! -f "$ANDROID_APK_PATH" ]; then
                echo "? APK file not found!"
                exit 1
            fi
            
            # Install Firebase CLI
            echo "Installing Firebase CLI..."
            npm install -g firebase-tools
            
            # Check Firebase CLI version
            firebase --version
            
            # Upload to Firebase App Distribution with testers group
            echo "Starting upload..."
            firebase appdistribution:distribute "$ANDROID_APK_PATH" \
              --app "$FIREBASE_APP_ID_ANDROID" \
              --token "$FIREBASE_TOKEN" \
              --groups "testers" \
              --release-notes "VoteEasy Android Build - Branch: $BITRISE_GIT_BRANCH, Build: #$BITRISE_BUILD_NUMBER, Commit: $GIT_CLONE_COMMIT_HASH" \
              --debug
            
            EXIT_CODE=$?
            
            if [ $EXIT_CODE -eq 0 ]; then
                echo "? Successfully uploaded to Firebase App Distribution!"
                echo "?? Testers in 'testers' group will receive notification"
            else
                echo "? Firebase upload failed with exit code: $EXIT_CODE"
                echo "Check Firebase Console and token validity"
                exit $EXIT_CODE
            fi
    
    # 12. Створити інструкцію для запуску
    - script@1:
        title: Create installation instructions
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            cat > $BITRISE_DEPLOY_DIR/INSTALL_INSTRUCTIONS.txt << 'EOF'
            ?? VoteEasy Android Release Build
            
            ?? Файл: VoteEasy.apk
            
            ?? Як встановити на Android:
            
            1. Завантажте VoteEasy.apk
            2. На Android пристрої:
               - Дозвольте установку з невідомих джерел (Settings > Security)
               - Відкрийте APK файл
               - Натисніть "Install"
            
            3. Або через Firebase App Distribution:
               - Отримайте запрошення на email
               - Встановіть Firebase App Distribution app
               - Завантажте build через додаток
            
            4. Або через ADB (для емулятора/developer):
               adb install VoteEasy.apk
            
            ? Готово! Застосунок встановлений
            EOF
            
            echo "? Installation instructions created"
    
    # 13. Deploy артефактів
    - deploy-to-bitrise-io@2:
        inputs:
        - notify_user_groups: none
        - is_compress: 'false'

app:
  envs:
  - BITRISE_FLUTTER_PROJECT_LOCATION: "voteeasy"
    opts:
      is_expand: false
  - FLUTTER_VERSION: stable
    opts:
      is_expand: false
