// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp6Sqs41j7AYvCIEcLBg9g3fOPxfqIt5A',
    appId: '1:768252539367:web:ea9882537849b70e4a0d42',
    messagingSenderId: '768252539367',
    projectId: 'voteeasy-app1',
    authDomain: 'voteeasy-app1.firebaseapp.com',
    storageBucket: 'voteeasy-app1.firebasestorage.app',
    measurementId: 'G-LVZ6J2STMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIrJmCqsedhD_FBME6vVoIgGybQboCX-0',
    appId: '1:768252539367:android:3d680b29de0c2cbe4a0d42',
    messagingSenderId: '768252539367',
    projectId: 'voteeasy-app1',
    storageBucket: 'voteeasy-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEYuL36pBAik6Kzb75C4eDz02qo4Af174',
    appId: '1:768252539367:ios:ad867f23d7dd50704a0d42',
    messagingSenderId: '768252539367',
    projectId: 'voteeasy-app1',
    storageBucket: 'voteeasy-app1.firebasestorage.app',
    iosBundleId: 'com.example.voteeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEYuL36pBAik6Kzb75C4eDz02qo4Af174',
    appId: '1:768252539367:ios:ad867f23d7dd50704a0d42',
    messagingSenderId: '768252539367',
    projectId: 'voteeasy-app1',
    storageBucket: 'voteeasy-app1.firebasestorage.app',
    iosBundleId: 'com.example.voteeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp6Sqs41j7AYvCIEcLBg9g3fOPxfqIt5A',
    appId: '1:768252539367:web:d7bd90e84d335d504a0d42',
    messagingSenderId: '768252539367',
    projectId: 'voteeasy-app1',
    authDomain: 'voteeasy-app1.firebaseapp.com',
    storageBucket: 'voteeasy-app1.firebasestorage.app',
    measurementId: 'G-B0Q1PE1BHT',
  );
}
